### ISSUE TITLE
source code of service broker

### ISSUE THREAD

**Issue by comxtohr** [slowbackspace/mongo-boshrelease#1]
Hi, I'm trying to deploy this repo in my own cloud foundry, however i noticed that there is something wrong with the service broker. So could you tell me where I can find the soure code of the service broker using in this repo? Thanks a lot! @slowbackspace

**Comment by slowbackspace** [comment]
https://github.com/slowbackspace/mongo-broker

It should be mostly the same as 
https://github.com/spring-cloud-samples/cloudfoundry-service-broker

I think I added loading broker's plan from yml file (properties are taken from the deployment manifest and copied to catalog.yml file in `/var/vcap/packages/cf-mongodb-broker/cf-mongodb-broker/` directory) and MongoClient uses multiple ips to connect to replica set.

Properties from my deployment manifest:

```
properties:
  broker:
    host: p-mongodb.DOMAIN
    security_user_name: broker
    security_user_password: BROKER_PASSWORD
    id: mongodb-service-broker
    name: mongodb
    description: MongoDB databases on demand
    bindable: true
    plan_updateable: false

    plans:
    - id: mongo-developer-plan
      name: standard
      description: Shared MongoDB Server
      metadata:
        bullets:
        - Shared MongoDB (3.2.9) replica set
        costs:
        - amount:
            usd: 0
          unit: month
      free: true

    tags:
    - mongodb

    metadata:
      displayName: MongoDB
      imageUrl: http://info.mongodb.com/rs/mongodb/images/MongoDB_Logo_Full.png
      longDescription: Creating a service instance provisions a database. Binding
        applications provisions unique credentials for each application to access
        the database.
      providerDisplayName: myAwesomeCF
      documentationUrl: null
      supportUrl: null

    requires: null
    dashboard_client: null
``` 

I recall that errand for registering the broker doesn't work.
